name: BlockyWhitelist
version: '${project.version}'
main: me.fami6xx.blockywhitelist.BlockyWhitelist
api-version: '1.20'
depend:
  - RPUniverse
  - Vault
libraries:
  - 'com.google.code.gson:gson:2.10.1'
  - 'net.dv8tion:JDA:5.3.0'
commands:
  blockywhitelist:
    description: Main command for BlockyWhitelist
    usage: /<command>
    aliases:
      - bwl
permissions:
  blockywhitelist.use:
    description: Allows the player to use the /blockywhitelist command
  blockywhitelist.ignore:
    description: Allows the player to ignore the whitelist
